image: docker:stable

services:
  - docker:stable-dind

variables:
  REGISTRY: registry.gitlab.com
  REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  IMAGE: admin-ui

stages:
  - test
  - build
  - release

test:
  services:
    - name: jboss/keycloak
      alias: keycloak.local
  variables:
    KEYCLOAK_USER: wwwy3y3
    KEYCLOAK_PASSWORD: wwwy3y3
  image:
    name: wwwy3y3/minikube-ci-node:8
    # override the default command. so that gitlab-ci can run the shell
    entrypoint: []
  stage: test
  only:
    - master
  before_script:
    - date
    # start minikube
    - sudo bash ci/start.sh &
  script:
     # Check keycloak endpoints
    - date
    - sudo bash ci/keycloak-endpoint.sh

    # Wait for minikube ready
    - >
      JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
      until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True";
      do sleep 1;
      done

    # install and run test
    - cd server && yarn && KC_MAX_SOCKETS=30 KC_API_BASEURL=http://keycloak.local:8080/auth KC_OIDC_BASEURL=http://keycloak.local:8080/auth npm run test
    # run e2e
    - echo "e2e test"
    - cd server && npm run test:e2e
  after_script:
    - date

build:
  stage: build
  script:
    - echo "${DOCKER_DRIVER}"
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${REGISTRY}"
    - docker pull "${REGISTRY}/${REPOSITORY}/${IMAGE}:${CI_COMMIT_BEFORE_SHA:0:7}" || true
    - docker build -t "${REGISTRY}/${REPOSITORY}/${IMAGE}:${CI_COMMIT_SHA:0:7}" .
    - docker push "${REGISTRY}/${REPOSITORY}/${IMAGE}:${CI_COMMIT_SHA:0:7}"
  only:
    - master

release:tag:
  stage: release
  script:
    - echo "${DOCKER_DRIVER}"
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${REGISTRY}"
    - docker pull "${REGISTRY}/${REPOSITORY}/${IMAGE}:${CI_COMMIT_SHA:0:7}" || true
    - docker build -t "${REGISTRY}/${REPOSITORY}/${IMAGE}:${CI_COMMIT_TAG}" .
    - docker push "${REGISTRY}/${REPOSITORY}/${IMAGE}:${CI_COMMIT_TAG}"
  only:
    - tags
