version: 2.1
orbs:
  docker: circleci/docker@1.2.0
commands:
  build_console:
    description: "Build primehub-console images and Push to dockerhub"
    parameters:
      tag:
        type: string
    steps:
      - docker/check
      # Build and push Primehub-console EE image
      - docker/build:
          step-name: 'Docker build: primehub-console'
          image: 'infuseai/primehub-console'
          tag: << parameters.tag >>
          dockerfile: 'packages/admin-server/Dockerfile'
      - docker/push:
          step-name: 'Docker push: primehub-console'
          image: 'infuseai/primehub-console'
          tag: << parameters.tag >>
      - docker/push:
          step-name: 'Docker push: primehub-console'
          image: 'infuseai/primehub-console'
  build_console_others:
    description: "Build primehub-console images and Push to dockerhub"
    parameters:
      tag:
        type: string
    steps:
      - docker/check
      # Build and push Primehub-console EE(Model Deployment only version) image
      - docker/build:
          step-name: 'Docker build: primehub-console(model-deployment only)'
          image: 'infuseai/primehub-console-model-deploy'
          tag: << parameters.tag >>
          dockerfile: 'packages/admin-server/overlay/model_deployment/Dockerfile'
      - docker/push:
          step-name: 'Docker push: primehub-console(model-deployment only)'
          image: 'infuseai/primehub-console-model-deploy'
          tag: << parameters.tag >>
      - docker/push:
          step-name: 'Docker push: primehub-console(model-deployment only)'
          image: 'infuseai/primehub-console-model-deploy'
      # Build and push Primehub-console CE image
      - docker/build:
          step-name: 'Docker build: primehub-console (CE only)'
          image: 'infuseai/primehub-console-ce'
          tag: << parameters.tag >>
          dockerfile: 'packages/admin-server/overlay/ce/Dockerfile'
      - docker/push:
          step-name: 'Docker push: primehub-console (CE only)'
          image: 'infuseai/primehub-console-ce'
          tag: << parameters.tag >>
      - docker/push:
          step-name: 'Docker push: primehub-console (CE only)'
          image: 'infuseai/primehub-console-ce'
  build_watcher:
    description: "Build primehub-console-watcher images and Push to dockerhub"
    parameters:
      tag:
        type: string
    steps:
      - docker/check
      # Build and push Primehub-console Watcher image
      - docker/build:
          step-name: 'Docker build: primehub-console-watcher'
          image: 'infuseai/primehub-console-watcher'
          tag: << parameters.tag >>
          dockerfile: 'packages/watcher/Dockerfile'
      - docker/push:
          step-name: 'Docker push: primehub-console-watcher'
          image: 'infuseai/primehub-console-watcher'
          tag: << parameters.tag >>
      - docker/push:
          step-name: 'Docker push: primehub-console-watcher'
          image: 'infuseai/primehub-console-watcher'
  build_graphql:
    description: "Build primehub-console-graphql images and Push to dockerhub"
    parameters:
      tag:
        type: string
    steps:
      - docker/check
      # Build and push Primehub-console GraphQL EE image
      - docker/build:
          step-name: 'Docker build: primehub-console-graphql'
          image: 'infuseai/primehub-console-graphql'
          tag: << parameters.tag >>
          dockerfile: 'packages/graphql-server/docker/ee/Dockerfile'
      - docker/push:
          step-name: 'Docker push: primehub-console-graphql'
          image: 'infuseai/primehub-console-graphql'
          tag: << parameters.tag >>
      - docker/push:
          step-name: 'Docker push: primehub-console-graphql'
          image: 'infuseai/primehub-console-graphql'
      # Build and push Primehub-console GraphQL CE image
      - docker/build:
          step-name: 'Docker build: primehub-console-graphql(CE only)'
          image: 'infuseai/primehub-console-graphql-ce'
          tag: << parameters.tag >>
          dockerfile: 'packages/graphql-server/docker/ce/Dockerfile'
      - docker/push:
          step-name: 'Docker push: primehub-console-graphql(CE only)'
          image: 'infuseai/primehub-console-graphql-ce'
          tag: << parameters.tag >>
      - docker/push:
          step-name: 'Docker push: primehub-console-graphql(CE only)'
          image: 'infuseai/primehub-console-graphql-ce'

jobs:
  # Latest
  latest-console:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_console:
          tag: 'latest'
  latest-console-others:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_console_others:
          tag: 'latest'
  latest-graphql:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_graphql:
          tag: 'latest'
  latest-watcher:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_watcher:
          tag: 'latest'
  # Release
  release-console:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_console:
          tag: $CIRCLE_TAG
  release-console-others:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_console_others:
          tag: $CIRCLE_TAG
  release-graphql:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_graphql:
          tag: $CIRCLE_TAG
  release-watcher:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - build_watcher:
          tag: $CIRCLE_TAG
  # Tests
  graphql-lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Running tslint & tsc dryrun tests for graphql
          command: |
            cd packages/graphql-server
            npm install
            npm run test:build

workflows:
  version: 2
  build_and_push:
    jobs:
      - graphql-lint:
          filters:
            tags:
              only: /.*/
      - latest-console:
          requires:
            - graphql-lint
          filters:
            branches:
              only:
                - master
      - latest-console-others:
          requires:
            - graphql-lint
          filters:
            branches:
              only:
                - master
      - latest-graphql:
          requires:
            - graphql-lint
          filters:
            branches:
              only:
                - master
      - latest-watcher:
          requires:
            - graphql-lint
          filters:
            branches:
              only:
                - master
      - release-console:
          requires:
            - graphql-lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release-console-others:
          requires:
            - graphql-lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release-graphql:
          requires:
            - graphql-lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release-watcher:
          requires:
            - graphql-lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
