version: 2.1
orbs:
  docker: circleci/docker@1.2.0
commands:
  build_all:
    description: "Build all images and Push to dockerhub"
    parameters:
      tag:
        type: string
    steps:
      - docker/check
      # Build and push Primehub-console EE image
      - docker/build:
          image: 'infuseai/primehub-console'
          tag: << parameters.tag >>
          dockerfile: 'packages/admin-server/Dockerfile'
      - docker/push:
          image: 'infuseai/primehub-console'
          tag: << parameters.tag >>
      # Build and push Primehub-console EE(Model Deployment only version) image
      - docker/build:
          image: 'infuseai/primehub-console-model-deploy'
          tag: << parameters.tag >>
          dockerfile: 'packages/admin-server/overlay/model_deployment/Dockerfile'
      - docker/push:
          image: 'infuseai/primehub-console-model-deploy'
          tag: << parameters.tag >>
      # Build and push Primehub-console CE image
      - docker/build:
          image: 'infuseai/primehub-console-ce'
          tag: << parameters.tag >>
          dockerfile: 'packages/admin-server/overlay/ce/Dockerfile'
      - docker/push:
          image: 'infuseai/primehub-console-ce'
          tag: << parameters.tag >>
      # Build and push Primehub-console Watcher image
      - docker/build:
          image: 'infuseai/primehub-console-watcher'
          tag: << parameters.tag >>
          dockerfile: 'packages/watcher/Dockerfile'
      - docker/push:
          image: 'infuseai/primehub-console-watcher'
          tag: << parameters.tag >>
      # Build and push Primehub-console GraphQL EE image
      - docker/build:
          image: 'infuseai/primehub-console-graphql'
          tag: << parameters.tag >>
          dockerfile: 'packages/graphql-server/docker/ee/Dockerfile'
      - docker/push:
          image: 'infuseai/primehub-console-graphql'
          tag: << parameters.tag >>
      # Build and push Primehub-console GraphQL CE image
      - docker/build:
          image: 'infuseai/primehub-console-graphql-ce'
          tag: << parameters.tag >>
          dockerfile: 'packages/graphql-server/docker/ce/Dockerfile'
      - docker/push:
          image: 'infuseai/primehub-console-graphql-ce'
          tag: << parameters.tag >>

jobs:
  latest:
    docker:
      - image: docker:18-dind
    steps:
      - checkout
      - setup_remote_docker
      - build_all:
          tag: 'latest'

  release:
    docker:
      - image: docker:18-dind
    steps:
      - checkout
      - setup_remote_docker
      - build_all:
          tag: $CIRCLE_TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - latest:
          filters:
            branches:
              only:
                - master
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
