apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dataset.primehub.io
spec:
  group: primehub.io
  version: v1alpha1
  names:
    kind: Dataset
    plural: datasets
    singular: dataset
  scope: Namespaced
