apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: image.primehub.io
spec:
  group: primehub.io
  version: v1alpha1
  names:
    kind: Image
    plural: images
    singular: image
  scope: Namespaced
