apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instancetype.primehub.io
spec:
  group: primehub.io
  version: v1alpha1
  names:
    kind: InstanceType
    plural: instancetypes
    singular: instancetype
  scope: Namespaced
