apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  selector:
    app: primehub-console-test-keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  selector:
    app: primehub-console-test-minio
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 9000
